// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseCurrentFile():Promise<void>;

export function Exit():Promise<void>;

export function GetAppState():Promise<main.AppState>;

export function GetCurrentDirectory():Promise<string>;

export function GetCurrentFile():Promise<string>;

export function GetFileContent():Promise<string>;

export function GetFileName():Promise<string>;

export function GetFiles():Promise<Array<main.ExcalidrawFile>>;

export function IsDirty():Promise<boolean>;

export function LoadFile(arg1:string):Promise<string>;

export function NewFileDialog():Promise<void>;

export function OpenDirectoryDialog():Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveCurrentFile():Promise<void>;

export function SaveFile(arg1:string):Promise<void>;

export function UpdateFileContent(arg1:string):Promise<void>;
