// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseCurrentFile() {
  return window['go']['main']['App']['CloseCurrentFile']();
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function GetFileContent() {
  return window['go']['main']['App']['GetFileContent']();
}

export function GetFileName() {
  return window['go']['main']['App']['GetFileName']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function IsDirty() {
  return window['go']['main']['App']['IsDirty']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function NewFileDialog() {
  return window['go']['main']['App']['NewFileDialog']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveCurrentFile() {
  return window['go']['main']['App']['SaveCurrentFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function UpdateFileContent(arg1) {
  return window['go']['main']['App']['UpdateFileContent'](arg1);
}
